Vagrant.configure("2") do |config|

  # SSH Settings
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["keys/lamp-jammy.key", "~/.vagrant.d/insecure_private_key"]

  # Add public key
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("keys/lamp-jammy.key.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /home/vagrant/.ssh/
      touch /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} > /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant
      exit 0
    SHELL
  end

  config.vm.box = "ubuntu/jammy64"
  config.vm.define "lamp-jammy"        # name first layer
  config.vm.hostname = "lamp-jammy"    # hostname

  config.vm.network "public_network", bridge: "wlp3s0",
    ip: "192.168.0.200",
    netmask:"255.255.255.0",
    gateway: "192.168.0.1"

  # VAGRANT_EXPERIMENTAL="disks"
  config.vm.disk :disk, name: "content", size: "20GB"

  config.vm.provider "virtualbox" do |vb|

     vb.name = "lamp-jammy"            # name in VirtualBox

     vb.memory = "2048"
     vb.cpus = 6

     vb.default_nic_type = "82543GC"

   end

  # default router
  config.vm.provision "shell", inline: <<-SHELL
    ip route del default via 10.0.2.2
  SHELL

  # Ansible Settings
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/hosts"
  end

end
