Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "lamp"        # name first layer
  config.vm.hostname = "lamp"    # hostname

  config.vm.network "public_network", bridge: "wlp3s0",
    use_dhcp_assigned_default_route: true

  # VAGRANT_EXPERIMENTAL="disks"
  config.vm.disk :disk, name: "content", size: "20GB"

  config.vm.provider "virtualbox" do |vb|

     vb.name = "lamp-jammy"            # name in VirtualBox

     vb.memory = "2048"
     vb.cpus = 6

     vb.default_nic_type = "82543GC"

   end

  # default router
  config.vm.provision "shell", inline: <<-SHELL
    ip route del default via 10.0.2.2
  SHELL

  # Ansible Settings
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

end
