Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.define "web"        # name in vagrant
  config.vm.hostname = "web"    # hostname

  config.vm.network "public_network", bridge: "wlp3s0",
    use_dhcp_assigned_default_route: true

  # VAGRANT_EXPERIMENTAL="disks"
  config.vm.disk :disk, name: "content", size: "20GB"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "web-jammy"            # name in VirtualBox

    vb.memory = "2048"
    vb.cpus = 6

    vb.default_nic_type = "82543GC"

   end

  # Delete route via NAT interface
  config.vm.provision "shell", inline: <<-SHELL
    ip route del default via 10.0.2.2
  SHELL

  # Install LAMP
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install lsb-release ca-certificates apt-transport-https software-properties-common -y
    add-apt-repository ppa:ondrej/php -y
    apt-get update
    # Install Apache
    apt-get install apache2 apache2-utils -y
    # Add content disk
    parted /dev/sdc mklabel msdos
    parted /dev/sdc mkpart primary ext4 10MiB 100%
    mkfs.ext4 /dev/sdc1
    mount /dev/sdc1 /var/www/html/
    # Create files for testing
    chmod -R 0777 /var/www/html/
    echo "<h1>Test page</h1>" > /var/www/html/index.html
    echo "<?php phpinfo(); ?>" > /var/www/html/info.php
    chown -R www-data: /var/www/html
    systemctl enable apache2 && systemctl start apache2
    # Install DB
    apt-get install mariadb-server mariadb-client
    systemctl enable mariadb && systemctl start mariadb
    # Install PHP
    apt-get install php8.1 php8.1-fpm libapache2-mod-php8.1 php8.1-mysql php-common php8.1-cli php8.1-common php8.1-opcache php8.1-readline php8.1-mbstring php8.1-xml php8.1-gd php8.1-curl -y
    a2enmod proxy_fcgi setenvif
    a2enconf php8.1-fpm
    systemctl restart apache2

  SHELL

end
