Vagrant.configure("2") do |config|

  # SSH Settings
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["keys/rancher-cluster.key", "~/.vagrant.d/insecure_private_key"]

  # Add public key
  config.vm.provision "shell" do |key|
    ssh_pub_key = File.readlines("keys/rancher-cluster.key.pub").first.strip
    key.inline = <<-SHELL
      mkdir -p /home/vagrant/.ssh/
      touch /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} > /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant
      exit 0
    SHELL
  end

  # Ansible Settings
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/hosts"
  end

#------------------ RANCHER ------------------------------------------
  config.vm.define "rancher" do |rancher|
    #rancher.vm.box = "ubuntu/focal64"
    rancher.vm.box = "ubuntu/jammy64"
    rancher.vm.hostname = "rancher"

    rancher.vm.synced_folder ".", "/vagrant", disabled: true

    rancher.vm.network "public_network", bridge: "wlp3s0",
      ip: "192.168.0.200",
      netmask:"255.255.255.0",
      gateway: "192.168.0.1"

    rancher.vm.network "private_network",
      ip: "192.168.56.200",
      netmask:"255.255.248.0"

    rancher.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "rancher"
      virtualbox.memory = "4096"
      virtualbox.cpus = 3

      virtualbox.default_nic_type = "82543GC"
    end # end provider

     rancher.vm.provision "shell", inline: <<-SHELL
       ip route del default via 10.0.2.2
     SHELL

  end # end define
#------------------------------------------------------------
#
#---------------------- NODES -------------------------------------
  (1..3).each do |i|
    config.vm.define "node-00#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = "node-00#{i}"

      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.network "private_network",
        ip: "192.168.56.20#{i}",
        netmask:"255.255.248.0"

      node.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name = "node-00#{i}"
        virtualbox.memory = "2048"
        virtualbox.cpus = 3

        virtualbox.default_nic_type = "82543GC"
      end # end provider

    end # end define

  end # end loop

#---------------------------------------------------------------------#

end
